import { Playfair_Display } from "next/font/google";
import Link from "next/link";
import Navbar from "@/app/components/Navbar";

const playfair = Playfair_Display({ subsets: ["latin"], weight: ["600", "700"] });

const LAST_UPDATED = "27 May 2026";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#050505] text-white selection:bg-[#C9A84C]/30">
      <Navbar />
      <div className="mx-auto w-full max-w-3xl px-6 py-20 sm:px-8">
        <p className="text-xs font-semibold uppercase tracking-[0.25em] text-[#C9A84C]">Legal</p>
        <h1 className={`${playfair.className} mt-4 text-4xl font-bold text-white sm:text-5xl`}>
          Terms of Service
        </h1>
        <p className="mt-4 text-xs text-neutral-500">Last updated: {LAST_UPDATED}</p>
        <p className="mt-6 text-base leading-8 text-neutral-400">
          Please read these terms carefully before using Lexalyze. By accessing or using this service, you agree to be bound by these terms.
        </p>

        <div className="mt-12 space-y-10 border-t border-white/[0.06] pt-10">

          <section>
            <h2 className={`${playfair.className} text-xl font-semibold text-[#C9A84C]`}>1. Nature of the service</h2>
            <div className="mt-4 space-y-3 text-sm leading-7 text-neutral-400">
              <p>Lexalyze is an independent AI-powered tool that helps users understand legal documents. It is <strong className="text-neutral-200">not a law firm</strong> and does not provide legal advice.</p>
              <p>The analyses generated by Lexalyze are produced by a large language model (AI) and are provided for <strong className="text-neutral-200">informational and educational purposes only</strong>. They do not constitute legal advice, legal opinions, or representation.</p>
            </div>
          </section>

          <section>
            <h2 className={`${playfair.className} text-xl font-semibold text-[#C9A84C]`}>2. No legal advice</h2>
            <div className="mt-4 space-y-3 text-sm leading-7 text-neutral-400">
              <p>Nothing on Lexalyze should be construed as legal advice. The AI analysis is a starting point for understanding, not a substitute for professional legal counsel. For any significant legal decision — including signing contracts, responding to notices, or taking legal action — please consult a qualified advocate or lawyer licensed in your jurisdiction.</p>
              <p>Lexalyze expressly disclaims all liability for any decisions made or actions taken in reliance on the information provided by the service.</p>
            </div>
          </section>

          <section>
            <h2 className={`${playfair.className} text-xl font-semibold text-[#C9A84C]`}>3. AI limitations</h2>
            <div className="mt-4 space-y-3 text-sm leading-7 text-neutral-400">
              <p>AI language models can and do make mistakes. Lexalyze may:</p>
              <ul className="space-y-2">
                <li className="flex items-start gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A84C]/60" />Misinterpret ambiguous contractual language</li>
                <li className="flex items-start gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A84C]/60" />Miss nuances specific to state-level laws or recent amendments</li>
                <li className="flex items-start gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A84C]/60" />Produce incorrect risk assessments for unusual or highly technical documents</li>
                <li className="flex items-start gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A84C]/60" />Be unable to extract text accurately from scanned or image-based PDFs</li>
              </ul>
              <p>Always verify findings independently. The confidence scores and risk ratings are AI estimates, not definitive legal assessments.</p>
            </div>
          </section>

          <section>
            <h2 className={`${playfair.className} text-xl font-semibold text-[#C9A84C]`}>4. User responsibilities</h2>
            <div className="mt-4 space-y-3 text-sm leading-7 text-neutral-400">
              <p>By using Lexalyze, you agree that you will:</p>
              <ul className="space-y-2">
                <li className="flex items-start gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A84C]/60" />Only upload documents you have the right to analyse</li>
                <li className="flex items-start gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A84C]/60" />Not use the service for any unlawful purpose</li>
                <li className="flex items-start gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A84C]/60" />Not attempt to reverse-engineer, scrape, or abuse the service</li>
                <li className="flex items-start gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#C9A84C]/60" />Not upload documents containing information belonging to third parties without their consent</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className={`${playfair.className} text-xl font-semibold text-[#C9A84C]`}>5. No warranty</h2>
            <p className="mt-4 text-sm leading-7 text-neutral-400">
              The service is provided &quot;as is&quot; without any warranties, express or implied. We do not guarantee the accuracy, completeness, or reliability of any AI-generated analysis. The service may be unavailable from time to time due to maintenance or technical issues.
            </p>
          </section>

          <section>
            <h2 className={`${playfair.className} text-xl font-semibold text-[#C9A84C]`}>6. Limitation of liability</h2>
            <p className="mt-4 text-sm leading-7 text-neutral-400">
              To the maximum extent permitted by applicable law, Lexalyze and its developers shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of or inability to use the service, or from any reliance on AI-generated analysis.
            </p>
          </section>

          <section>
            <h2 className={`${playfair.className} text-xl font-semibold text-[#C9A84C]`}>7. Changes to terms</h2>
            <p className="mt-4 text-sm leading-7 text-neutral-400">
              These terms may be updated from time to time. Continued use of the service after any changes constitutes your acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className={`${playfair.className} text-xl font-semibold text-[#C9A84C]`}>8. Contact</h2>
            <p className="mt-4 text-sm leading-7 text-neutral-400">
              Questions about these Terms of Service? Contact us at{" "}
              <a href="mailto:lexalyze.ai@gmail.com" className="text-[#C9A84C] hover:underline">lexalyze.ai@gmail.com</a>.
            </p>
          </section>
        </div>

        <div className="mt-12 flex flex-wrap gap-4">
          <Link href="/" className="text-sm font-medium text-[#C9A84C] hover:underline">← Back to home</Link>
          <Link href="/privacy" className="text-sm font-medium text-neutral-400 hover:text-white">Privacy Policy →</Link>
        </div>
      </div>
    </main>
  );
}
